name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: packages/build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: cd ../.. && npm ci

      - name: Setup
        run: npm run setup

      - name: Check
        run: npm run check

      - name: Test
        run: npm run test

  theme:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: packages/theme
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: cd ../.. && npm ci && cd packages/build && npm run build

      - name: Setup
        run: npm run setup

      - name: Check
        run: npm run check

      - name: Test
        run: npm run test

  action-timeline:
    needs:
      - build
      - theme
    permissions:
      actions: read
    runs-on: ubuntu-22.04
    steps:
      - uses: Kesin11/actions-timeline@v2
